Changed private to public for Angular
revaturelabs/Interview-Tracker-Angular pull request #132
Opened 2020-01-31 19:04 UTC by erichunsinger

2020-01-31 19:05 UTC, erichunsinger commented
changed service variables from public to private while leaving the service methods public

2020-02-04 18:53 UTC, IkenoXamos commented on src/app/Job-Service/job.service.ts
> +  public url = 'http://localhost:8765/interview-service/jobs';
Do the member variables of a service need to be public?

2020-02-04 18:53 UTC, IkenoXamos commented on src/app/profile.service.ts
> +    public url1 = 'http://localhost:8765/interview-service/profiles/allProfiles';
Do the member variables of a service need to be public?

2020-02-04 18:53 UTC, IkenoXamos commented on src/app/skill.service.ts
> +  public url1 = 'http://localhost:8765/interview-service/skills/allSkills';
Do the member variables of a service need to be public?

2020-02-04 18:54 UTC, IkenoXamos requested changes
As far as I can tell the member variables of a service should remain private, and only the member variables of a component should be public. This is in order for that field to be accessible for databinding. Since services don't have a template, there is no need for any databinding to occur for a service's member variables.

2020-02-04 20:18 UTC, closed without merging